local WorldsConfig = {}

WorldsConfig.Worlds = {
    [1] = {
        BaseplateColor = Color3.fromRGB(22, 211, 35);
        CashPerStud = 1;
        PublicName = "Forest";
        PriceInWins = 0;
        Index = 1;
        JumpMultiplier = 2;
        BaseWins = 1;
        MultiplierWins = 3;
    };
    [2] = {
        BaseplateColor = Color3.fromRGB(194, 235, 228);
        CashPerStud = 1.5;
        PublicName = "Winter";
        PriceInWins = 100;
        Index = 2;
        JumpMultiplier = 1;
        BaseWins = 2;
        MultiplierWins = 4;
    };
}

return WorldsConfig